#!/usr/bin/env python3
"""
BizNode – Digital Business Operator
Copyright 2026 1BZ DZIT DAO LLC

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at:

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.

---

BizNode Setup Script
===================
Interactive setup wizard that collects business information
and configures the BizNode for first-time use.
"""

import os
import sys
import json
import getpass
from pathlib import Path

# Add current directory to path
sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))


def print_header(text):
    """Print a formatted header."""
    print("\n" + "=" * 60)
    print(f"  {text}")
    print("=" * 60 + "\n")


def print_success(text):
    """Print success message."""
    print(f"✅ {text}")


def print_error(text):
    """Print error message."""
    print(f"❌ {text}")


def print_info(text):
    """Print info message."""
    print(f"ℹ️  {text}")


def get_input(prompt, default=None, required=True, password=False):
    """Get user input with validation."""
    if default:
        prompt = f"{prompt} [{default}]: "
    else:
        prompt = f"{prompt}: "
    
    while True:
        if password:
            value = getpass.getpass(prompt)
        else:
            value = input(prompt).strip()
        
        if not value and default:
            value = default
        
        if not value and required:
            print_error("This field is required. Please try again.")
            continue
        
        return value


def get_telegram_id():
    """Get and validate Telegram ID."""
    while True:
        value = input("Owner Telegram ID (e.g., 123456789): ").strip()
        
        if not value:
            print_error("Telegram ID is required.")
            continue
        
        # Check if it's numeric
        if value.lstrip('-').isdigit():
            return value
        
        print_error("Invalid Telegram ID. Please enter a numeric ID_email():
.")


def get    """Get and validate email address."""
    while True:
        value = input("Email address: ").strip()
        
        if not value:
            print_error("Email is required.")
            continue
        
        # Basic email validation
        if '@' in value and '.' in value.split('@')[1]:
            return value
        
        print_error("Invalid email format. Please try again.")


def get_port():
    """Get and validate port number."""
    while True:
        value = input("API Port [5000]: ").strip() or "5000"
        
        if value.isdigit():
            port = int(value)
            if 1024 <= port <= 65535:
                return str(port)
        
        print_error("Invalid port. Please enter a number between 1024-65535.")


def create_env_file(config):
    """Create .env file with configuration."""
    print_info("Creating .env file...")
    
    env_content = f"""# BizNode Environment Configuration
# ============================================================
# Generated by setup.py on {config['timestamp']}

# === Telegram Configuration ===
TELEGRAM_BOT_TOKEN={config['telegram_bot_token']}
OWNER_TELEGRAM_ID={config['owner_telegram_id']}

# === Node Configuration ===
NODE_PASSWORD={config.get('node_password', '')}
NODE_ID={config.get('node_id', '')}

# === Ollama LLM Configuration ===
OLLAMA_URL=http://localhost:11434/api/generate
OLLAMA_EMBED_URL=http://localhost:11434/api/embeddings
LLM_MODEL=qwen2.5
EMBEDDING_MODEL=nomic-embed-text

# === Qdrant Vector Database ===
QDRANT_HOST=localhost
QDRANT_PORT=6333

# === SQLite Database ===
SQLITE_PATH=memory/biznode.db

# === Email (SMTP) Configuration ===
SMTP_HOST={config['smtp_host']}
SMTP_PORT={config['smtp_port']}
SMTP_USER={config['smtp_user']}
SMTP_PASSWORD={config['smtp_password']}
AGENT_EMAIL={config['agent_email']}

# === AI Agent Identity ===
AGENT_NAME={config['agent_name']}
AUTONOMY_LEVEL=1

# === API Server ===
API_PORT={config.get('api_port', '5000')}

# === 1bz Network (Optional) ===
NETWORK_ENABLED=false
"""
    
    with open('.env', 'w') as f:
        f.write(env_content)
    
    print_success(".env file created")


def init_database(config):
    """Initialize SQLite database."""
    print_info("Initializing database...")
    
    try:
        from memory.database import init_db, save_agent_identity
        
        # Initialize tables
        init_db()
        print_success("Database tables created")
        
        # Save agent identity
        identity = {
            "agent_name": config['agent_name'],
            "agent_email": config['agent_email'],
            "telegram_bot_token": config['telegram_bot_token'],
            "smtp_host": config['smtp_host'],
            "smtp_port": int(config['smtp_port']),
            "smtp_user": config['smtp_user'],
            "smtp_password": config['smtp_password'],
            "owner_telegram_id": config['owner_telegram_id'],
            "owner_email": config['owner_email'],
            "autonomy_level": 1
        }
        
        save_agent_identity(identity)
        print_success("Agent identity saved to database")
        
    except Exception as e:
        print_error(f"Database initialization failed: {e}")
        return False
    
    return True


def create_config_json(config):
    """Create config.json for the API server."""
    print_info("Creating config.json...")
    
    config_json = {
        "agent_name": config['agent_name'],
        "agent_email": config['agent_email'],
        "owner_telegram_id": config['owner_telegram_id'],
        "owner_email": config['owner_email'],
        "telegram_bot_token": config['telegram_bot_token'],
        "smtp": {
            "host": config['smtp_host'],
            "port": int(config['smtp_port']),
            "user": config['smtp_user']
        },
        "autonomy_level": 1,
        "setup_timestamp": config['timestamp']
    }
    
    with open('config.json', 'w') as f:
        json.dump(config_json, f, indent=2)
    
    print_success("config.json created")


def start_docker():
    """Start Docker services."""
    print_info("Starting Docker services...")
    
    import subprocess
    
    try:
        # Check if docker is running
        result = subprocess.run(
            ['docker', 'info'],
            capture_output=True,
            text=True
        )
        
        if result.returncode != 0:
            print_error("Docker is not running. Please start Docker Desktop.")
            return False
        
        # Start services
        result = subprocess.run(
            ['docker-compose', 'up', '-d'],
            capture_output=True,
            text=True
        )
        
        if result.returncode == 0:
            print_success("Docker services started")
            return True
        else:
            print_error(f"Docker failed: {result.stderr}")
            return False
            
    except FileNotFoundError:
        print_error("docker-compose not found. Is Docker installed?")
        return False
    except Exception as e:
        print_error(f"Error starting Docker: {e}")
        return False


def update_help_file():
    """Update the help.md file with current configuration."""
    print_info("Updating help documentation...")
    
    help_content = """# BizNode Help

## Quick Reference

### Bot Commands

| Command | Description |
|---------|-------------|
| `/start` | Initialize the bot |
| `/status` | Check system health |
| `/help` | Show this help |
| `/register [business_name]` | Register a new business |
| `/search [query]` | Search memory |

### Contact Information

- **Agent Name**: {agent_name}
- **Agent Email**: {agent_email}
- **Owner**: {owner_email}

---

## Troubleshooting

### Bot Not Responding

1. Check if bot token is correct in `.env`
2. Verify the bot has been started (/start in Telegram)
3. Check logs: `docker compose logs biznode`

### Database Issues

1. Reinitialize: `python setup.py --reinit-db`
2. Check SQLite file: `ls -la memory/biznode.db`

### Docker Issues

1. Check status: `docker compose ps`
2. View logs: `docker compose logs -f`
3. Restart: `docker compose restart`

---

## Configuration

Configuration is stored in:
- `.env` - Environment variables
- `config.json` - API configuration
- `memory/biznode.db` - SQLite database

---

## Support

For issues and questions, visit the GitHub repository.
"""
    
    # Read current config if exists
    agent_name = "YourBizNode"
    agent_email = "ai@yourbiznode.1bz"
    owner_email = "owner@example.com"
    
    if os.path.exists('config.json'):
        try:
            with open('config.json', 'r') as f:
                cfg = json.load(f)
                agent_name = cfg.get('agent_name', agent_name)
                agent_email = cfg.get('agent_email', agent_email)
                owner_email = cfg.get('owner_email', owner_email)
        except:
            pass
    
    help_content = help_content.format(
        agent_name=agent_name,
        agent_email=agent_email,
        owner_email=owner_email
    )
    
    with open('help.md', 'w') as f:
        f.write(help_content)
    
    print_success("help.md updated")


def run_setup():
    """Main setup function."""
    print_header("BizNode Setup Wizard")
    
    print("""
Welcome to BizNode! This wizard will help you set up your
autonomous AI business agent.

You will need:
1. Telegram Bot Token (from @BotFather)
2. Agent Email configuration
3. Owner contact information
""")
    
    # Get configuration
    print_header("Step 1: Telegram Configuration")
    
    telegram_bot_token = get_input(
        "Telegram Bot Token",
        required=True,
        password=True
    )
    
    owner_telegram_id = get_telegram_id()
    
    print_header("Step 2: Agent Identity")
    
    agent_name = get_input(
        "Agent Name",
        default="MyBizNode"
    )
    
    agent_email = get_email()
    
    print_header("Step 3: Owner Information")
    
    owner_email = get_email()
    
    print_header("Step 4: Email Configuration")
    
    print("""
For Gmail, use App Password (not your regular password).
Get it from: Google Account > Security > App Passwords
""")
    
    smtp_host = get_input(
        "SMTP Host",
        default="smtp.gmail.com"
    )
    
    smtp_port = get_input(
        "SMTP Port",
        default="587"
    )
    
    smtp_user = get_input(
        "SMTP Username (your email)",
        default=owner_email
    )
    
    smtp_password = get_input(
        "SMTP Password/App Password",
        required=True,
        password=True
    )
    
    api_port = get_port()
    
    print_header("Step 5: Configuration Summary")
    
    # Build config dict
    config = {
        'timestamp': str(Path(__file__).stat().st_mtime),
        'telegram_bot_token': telegram_bot_token,
        'owner_telegram_id': owner_telegram_id,
        'agent_name': agent_name,
        'agent_email': agent_email,
        'owner_email': owner_email,
        'smtp_host': smtp_host,
        'smtp_port': smtp_port,
        'smtp_user': smtp_user,
        'smtp_password': smtp_password,
        'api_port': api_port
    }
    
    print(f"""
Please confirm your settings:

🤖 Agent Name: {agent_name}
📧 Agent Email: {agent_email}
👤 Owner Email: {owner_email}
📱 Owner Telegram: {owner_telegram_id}
📧 SMTP: {smtp_host}:{smtp_port}
🌐 API Port: {api_port}

Press Enter to continue or 'q' to quit...
""")
    
    confirm = input("> ")
    if confirm.lower() == 'q':
        print("Setup cancelled.")
        return
    
    # Execute setup steps
    print_header("Setting Up BizNode")
    
    # Create .env
    create_env_file(config)
    
    # Initialize database
    if not init_database(config):
        print_error("Setup failed at database initialization")
        return
    
    # Create config.json
    create_config_json(config)
    
    # Update help
    update_help_file()
    
    # Start Docker
    print("\n")
    start_docker = input("Start Docker services now? [Y/n]: ").strip().lower()
    if start_docker != 'n':
        start_docker()
    
    print_header("Setup Complete! 🎉")
    
    print("""
Your BizNode is now configured!

Next steps:
1. Start the bot: Send /start to your Telegram bot
2. Check status: Send /status to the bot
3. Configure Docker: docker compose up -d

For help: python setup.py --help
""")


def reinit_database():
    """Reinitialize the database."""
    print_info("Reinitializing database...")
    
    try:
        from memory.database import init_db, save_agent_identity
        
        # Load config
        if os.path.exists('config.json'):
            with open('config.json', 'r') as f:
                config = json.load(f)
            
            init_db()
            
            identity = {
                "agent_name": config.get('agent_name', 'BizNode'),
                "agent_email": config.get('agent_email', 'ai@biznode.1bz'),
                "telegram_bot_token": config.get('telegram_bot_token', ''),
                "smtp_host": config.get('smtp', {}).get('host', 'smtp.gmail.com'),
                "smtp_port": config.get('smtp', {}).get('port', 587),
                "smtp_user": config.get('smtp', {}).get('user', ''),
                "smtp_password": '',
                "owner_telegram_id": config.get('owner_telegram_id', ''),
                "owner_email": config.get('owner_email', ''),
                "autonomy_level": 1
            }
            
            save_agent_identity(identity)
            print_success("Database reinitialized")
        else:
            print_error("config.json not found. Run setup first.")
            
    except Exception as e:
        print_error(f"Error: {e}")


def show_status():
    """Show current configuration status."""
    print_header("BizNode Status")
    
    checks = [
        (".env", ".env file"),
        ("config.json", "config.json"),
        ("memory/biznode.db", "SQLite database"),
    ]
    
    for path, name in checks:
        if os.path.exists(path):
            print_success(f"{name} exists")
        else:
            print_error(f"{name} missing")
    
    # Check Docker
    import subprocess
    try:
        result = subprocess.run(
            ['docker', 'compose', 'ps', '--format', 'json'],
            capture_output=True,
            text=True
        )
        if result.returncode == 0:
            print_success("Docker is running")
        else:
            print_error("Docker not running")
    except:
        print_error("Docker not available")


def main():
    """Main entry point."""
    if len(sys.argv) > 1:
        if sys.argv[1] == '--reinit-db':
            reinit_database()
        elif sys.argv[1] == '--status':
            show_status()
        elif sys.argv[1] == '--help':
            print("""
BizNode Setup
=============

Usage:
  python setup.py              Run interactive setup
  python setup.py --status     Show configuration status
  python setup.py --reinit-db  Reinitialize database
  
  python setup.py --help       Show this help
""")
        else:
            print(f"Unknown option: {sys.argv[1]}")
    else:
        run_setup()


if __name__ == "__main__":
    main()
