"""
.env File Writer
================
Reads and writes structured .env files with section comments.
"""

import os
from typing import Dict


def read_env(path: str) -> Dict[str, str]:
    """Parse a .env file and return key→value dict."""
    result: Dict[str, str] = {}
    if not os.path.exists(path):
        return result
    with open(path, "r", encoding="utf-8") as f:
        for line in f:
            line = line.strip()
            if not line or line.startswith("#"):
                continue
            if "=" in line:
                k, _, v = line.partition("=")
                result[k.strip()] = v.strip().strip('"').strip("'")
    return result


def write_env(path: str, values: Dict[str, str]) -> None:
    """
    Write a clean, documented .env file.
    Sections are determined by key prefixes.
    """
    sections = [
        ("Telegram", ["TELEGRAM_BOT_TOKEN", "OWNER_TELEGRAM_ID"]),
        ("Ollama / LLM", [
            "OLLAMA_URL", "OLLAMA_EMBED_URL", "LLM_MODEL",
            "EMBEDDING_MODEL", "EMBEDDING_SIZE",
        ]),
        ("Qdrant Vector DB", ["QDRANT_HOST", "QDRANT_PORT"]),
        ("BizNode Agent", ["AGENT_NAME", "AUTONOMY_LEVEL", "OWNER_EMAIL"]),
        ("Email / SMTP", [
            "AGENT_EMAIL", "SMTP_HOST", "SMTP_PORT", "SMTP_USER", "SMTP_PASSWORD",
        ]),
        ("Security", ["NODE_PASSWORD", "NODE_SIGNING_KEY"]),
        ("Paths", ["SQLITE_PATH", "DATA_DIR"]),
    ]

    written: set = set()
    lines = [
        "# BizNode Configuration",
        "# Generated by BizNode Installer",
        "# Edit this file or use the dashboard at http://localhost:7777",
        "",
    ]

    for section_name, keys in sections:
        section_lines = []
        for key in keys:
            if key in values:
                section_lines.append(f"{key}={values[key]}")
                written.add(key)
        if section_lines:
            pad = max(0, 50 - len(section_name))
            lines.append(f"# ── {section_name} {'─' * pad}")
            lines.extend(section_lines)
            lines.append("")

    # Catch-all for any extra keys not in sections
    extras = [f"{k}={v}" for k, v in values.items() if k not in written]
    if extras:
        lines.append("# ── Other ───────────────────────────────────────────")
        lines.extend(extras)
        lines.append("")

    os.makedirs(os.path.dirname(os.path.abspath(path)), exist_ok=True)
    with open(path, "w", encoding="utf-8") as f:
        f.write("\n".join(lines))


def merge_env(base_path: str, overrides: Dict[str, str]) -> Dict[str, str]:
    """Read existing .env, apply overrides, return merged dict."""
    existing = read_env(base_path)
    return {**existing, **overrides}
